### ISSUE TITLE
HuskSync commands not working in the console

### ISSUE THREAD

**Issue by Shyruu** [WiIIiam278/HuskSync#417]
version of HuskSync : 3.6.8
Paper version : 1.20.4

Issue : no Husksync command works when using it on console (tried with migrate)
Plugin on the server:
![brave_VkQgpu61W3](https://github.com/user-attachments/assets/720593b0-4f98-4b09-aebc-29676bd0079a)

Message get:
![image](https://github.com/user-attachments/assets/2c96029a-602f-4270-92d1-d830bfa77547)

**Comment by Shyruu** [comment]
Tried with last alpha version. The plugin disables and the log says the version of HuskSync is for 1.21.3.

I tried with lower versions and the 3.6.4 works for 1.20.4 but the commands aren't working in console. Got the same message than before.

**Comment by WiIIiam278** [comment]
Unfortunately, your version of HuskSync is no longer supported and it seems this error is due to adventure-specific incompatibilities. The last supported HuskSync version for 1.20.4 should be 3.6.8, so you can give this version a try.

Please upgrade your server to a compatible version of Minecraft supported by HuskSync: https://william278.net/docs/husksync/compatibility

**Comment by Shyruu** [comment]
[https://i.imgur.com/62lW4Ic.png](url)

Still have the same problem, commands don't work on console. Do you think I can try it online ? If I lose my data and others players don't, it's actually fine.
